In [142]:
import pandas as pd
import numpy as np

Dataset Description

Following is a description of different columns in the dataset.

CRIM: per capita crime rate in the vicinity

ZN: amount of residential land reserved in the vicinity.

INDUS: proportion of industrial land reserved nearby (in square kilometers)

RIVERSIDE: If the boundary faces river side (= 1 if tract
bounds river; 0 otherwise)

POLINDEX: polution index

RM: number of rooms in the house.

AGE: Age of the property in years.

DIS: weighted distances to the major economic centres (in kilometers)

HIGHWAYCOUNT: Number of highways within 5 KM of distance.

TAX: full-value property-tax rate per 1 lac.

PTRATIO: student-teacher ratio in the vicinity.

IMM: Immigration index in the vicinity.

BPL: % of below poverty line population in the vicinity.

PRICE: Price of the home in lacs, this is the target column.

In [143]:
file_id = "1DRtaP8QnU7SFrhMsdR67TBNuq5aOusUe"
url = f"https://drive.google.com/uc?export=download&id={file_id}"

df = pd.read_csv(url)

In [144]:
df.sample(5)

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
562,0.455807,1.101106,28.688583,0.735511,7.0,94.0,3.108711,6,711.591619,20.398498,397.112955,18.175850,15.721135,NO
626,0.515695,0.305195,13.181106,0.560733,8.0,46.0,4.392105,5,398.512388,19.069147,388.189641,11.764127,21.263518,NO
1174,1.433255,31.520228,6.945120,0.979148,8.0,55.0,8.188059,7,300.212160,18.019134,373.122109,11.808948,22.356686,NO
1683,1.889964,0.017148,20.693596,1.969215,7.0,95.0,2.914924,5,404.140701,14.778762,293.217052,15.695102,18.054198,NO
2855,0.790362,0.227376,28.158215,2.767405,6.0,97.0,3.793500,2,188.582240,20.722326,370.633121,26.661019,18.651384,NO

How many samples are there in the dataset?

In [145]:
df.shape

(4000, 14)

What is the average house price (in lacs)?

In [146]:
f"{float(df["PRICE"].mean())}"

'24.355923220694248'

How many houses have 5 or more rooms?

In [147]:
int((df["RM"] >= 5).sum())

3953

What is the average price of the top 10 most expensive houses (in lacs)?

In [148]:
float(df["PRICE"].sort_values(ascending=False).head(10).mean())

52.36590175716407

What is the total number of missing or unknown values in the number of rooms feature?

In [149]:
df["RM"].nunique()

9

In [150]:
df["RM"].value_counts()

RM
 7.0     1733
 6.0      961
 8.0      894
 9.0      276
 5.0       47
 10.0      40
-1.0       40
 4.0        7
 11.0       2
Name: count, dtype: int64

In [151]:
df["RM"].isna().sum()

np.int64(0)

What is the total number of missing or unknown values in the age feature?

In [152]:
df["AGE"].isna().sum()

np.int64(0)

In [153]:
df["AGE"].nunique()

102

In [154]:
df["AGE"].unique()

array([ 42.,  63.,  -2.,   9.,  20.,  95.,  35.,  97.,  36.,  78.,  99.,
        96.,  19.,  73.,  86.,  37.,  76.,  50.,  32.,  92., 101.,   8.,
        94.,  84.,  47.,  43.,  65.,  46.,  59.,  74.,  93.,  80.,  98.,
       102.,  56., 100.,  89.,  53.,  18.,  71.,  62.,  83.,  66.,   7.,
        77.,  91.,  90.,  58.,  57.,  60.,  87.,  75.,  34.,  85.,  48.,
        33.,  38.,  30.,  23.,  55.,  11.,  14.,  45.,  41.,  88.,  16.,
        12.,  79.,  67.,  39.,  49.,  61.,  70.,  54.,  10.,  22.,  72.,
        15.,  51.,  81.,  31.,  52.,  44.,  28.,  17.,  40.,  29.,  69.,
        64.,  24.,  82.,  26.,  68.,  27.,  13., 103.,  21.,  25.,   6.,
         5.,   3.,   4.])

In [155]:
(df["AGE"] <= 0).sum()

np.int64(50)

What is the total number of missing or unknown values in the RIVERSIDE feature?

In [156]:
df["RIVERSIDE"].nunique()

3

In [157]:
df["RIVERSIDE"].value_counts()

RIVERSIDE
NO         3595
YES         317
UNKNOWN      88
Name: count, dtype: int64

How many houses are on riverside and were built within the last 50 years (i.e. a house 50 years old or younger)? For this question, ignore the rows that have missing values in either riverside feature or age feature.

In [158]:
df[((0 < df["AGE"]) & (df["AGE"] <= 50) & (df['RIVERSIDE'] == "YES"))].shape

(44, 14)

How many houses are near to exactly 6, 7 or 8 highways (all three inclusive)?

In [159]:
int(df['HIGHWAYCOUNT'].isin([6, 7, 8]).sum())

1211

Create a column 'CATEGORY' and divide the houses in categories as following:

Category 1: house price <10 lacs

Category 2: 10 lacs <= house price <20 lacs

Category 3: 20 lacs <= house price <30 lacs

Category 4: 30 lacs <= house price <40 lacs

Category 5: house price >=40 lacs

Which category has the highest number of records?

In [160]:
def category(price):
    if price < 10:
        return 1
    elif 10 <= price < 20:
        return 2
    elif 20 <= price < 30:
        return 3
    elif 30 <= price < 40:
        return 4
    else:
        return 5

df['CATEGORY'] = df['PRICE'].apply(category)

df["CATEGORY"].value_counts()

CATEGORY
3    2028
2    1158
4     503
5     268
1      43
Name: count, dtype: int64


5 points
Apply Pre processing
Divide the data into training and test sets

1. Replace the respective missing or unknown values in features room count, riverside and age with np.nan.
2. Keep 30% of the data as test set.
3. Use random_state as 0
4. PRICE is the target, rest of the columns are the features.
5. Apply train test split.
Hint: look for the documentation of the usual function that divides the data into training and test datasets.

What is the number of samples in the training set?

In [161]:
df[["RM", "RIVERSIDE", "AGE"]].fillna(np.nan, inplace=True)

/tmp/ipykernel_3614/474135224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["RM", "RIVERSIDE", "AGE"]].fillna(np.nan, inplace=True)

In [162]:
from sklearn.model_selection import train_test_split

X = df.drop("PRICE", axis=1)
y = df["PRICE"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=0
)

X_train.shape

(2800, 14)

Apply following preprocessing steps:

1. Drop CATEGORY column
2. CRIM: min max scaling
3. ZN: min max scaling
4. INDUS: standard scaling
5. POLINDEX: min max scaling
6. DIS: min max scaling
7. HIGHWAYCOUNT: min max scaling
8. TAX: min max scaling
9. PTRATIO: min max scaling
10. IMM: min max scaling
11. BPL: min max scaling
12. RM: impute with median then min max scaling
13. AGE: impute with mean then min max scaling
14. RIVERSIDE: Impute with most frequent value then one hot encode.

NOTE:
1. Make sure to preprocess the features in exactly above order. Answer of Q.16 depends upon correct order of featuring processing.
2. You may have to use multiple instances of a trasnformer for this question.


How many features are there after performing above transformation?

In [163]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

# Drop CATEGORY first
df = df.drop(columns=['CATEGORY'], axis = 1)

# Column groups
minmax_cols = ['CRIM', 'ZN', 'POLINDEX', 'DIS', 'HIGHWAYCOUNT',
               'TAX', 'PTRATIO', 'IMM', 'BPL']

standard_cols = ['INDUS']

rm_col = ['RM']
age_col = ['AGE']
river_col = ['RIVERSIDE']

minmax_pipeline = Pipeline([
    ('scaler', MinMaxScaler())
])

standard_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

rm_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', MinMaxScaler())
])

age_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', MinMaxScaler())
])

river_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('minmax', minmax_pipeline, minmax_cols),
    ('standard', standard_pipeline, standard_cols),
    ('rm', rm_pipeline, rm_col),
    ('age', age_pipeline, age_col),
    ('river', river_pipeline, river_col)
], remainder='drop')

X_processed = preprocessor.fit_transform(df)

X_processed.shape

(4000, 15)

In [165]:
X_processed[:5, :]

array([[ 0.07909526,  0.01405278,  0.19435802,  0.31740055,  0.15384615,
         0.17523887,  0.68900297,  0.99508149,  0.24918892, -0.49181501,
         0.58333333,  0.41904762,  1.        ,  0.        ,  0.        ],
       [ 0.06490115,  0.00251068,  0.22415346,  0.24393777,  0.26923077,
         0.22893296,  0.41296404,  0.94096921,  0.28324361, -0.72441309,
         0.66666667,  0.61904762,  1.        ,  0.        ,  0.        ],
       [ 0.86547041,  0.00433499,  0.64501063,  0.09675441,  0.92307692,
         0.91153062,  0.66006632,  0.96572315,  0.51100474,  1.04212217,
         0.75      ,  0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.04193844,  0.01023791,  0.10392356,  0.44523229,  0.11538462,
         0.22526312,  0.61175492,  0.97750908,  0.12409299, -0.01374487,
         0.58333333,  0.1047619 ,  1.        ,  0.        ,  0.        ],
       [ 0.06942711,  0.79834087,  0.16631961,  0.70510904,  0.        ,
         0.24503444,  0.40397789,  0.98763911,  0.25993983, -1.1038177 ,
         0.75      ,  0.20952381,  1.        ,  0.        ,  0.        ]])

In [166]:
float(X_processed.mean().mean())

0.37133690480839293

In [167]:
file_id = "1OtwemNuw0qilXAutyuZEjOscZVKuD7Tv"
url = f"https://drive.google.com/uc?export=download&id={file_id}"

df = pd.read_csv(url)

In [169]:
df.sample(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
3004,0.035591,0.014989,-0.310740,0.222620,0.323826,0.148148,0.191941,0.595504,0.998088,0.175003,0.428571,0.515152,1.0,0.0,24.361167
2577,0.029756,0.030590,-1.212038,0.021459,0.115975,0.111111,0.011349,0.487245,0.990381,0.121059,0.857143,0.909091,1.0,0.0,37.995095
1821,0.165982,0.197530,-1.036187,0.080971,0.165764,0.185185,0.147810,0.043768,0.961941,0.199997,0.428571,0.979798,1.0,0.0,36.589649
4,0.144225,0.204918,-0.930790,0.148694,0.177490,0.259259,0.146832,0.111429,0.983448,0.286322,0.285714,0.616162,1.0,0.0,23.129426
2075,0.068462,0.007318,-0.525975,0.524877,0.400676,0.074074,0.090639,0.459083,0.990714,0.198000,0.714286,0.030303,1.0,0.0,25.121139


Split the dataset into train dataset and test dataset in the following manner
	Use train_test_split to split the dataset into train and test dataset with test size equal to 0.3(i.e.30%) and random_state equal to 42. Let other parameters have default values.
	Columns except the last column should be the feature matrix (X_train or X_test)
	Last column will be the label vector.

(Common instructions for Q.2, Q.3 and Q.4)

Train the ridge model on the training data with the following parameters:

alpha = 10

solver = 'saga'

tol = 1e-4

random_state = 42

Enter the value of
R
2
R
2
   score on the test dataset.

In [171]:
from sklearn.model_selection import train_test_split

In [172]:
df.shape

(4000, 15)

In [173]:
df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14'],
      dtype='object')

In [174]:
X = df.drop("14", axis = 1)
y = df["14"]

In [179]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)

In [185]:
from sklearn.linear_model import Ridge

rid = Ridge(
    alpha = 10,
    solver = 'saga',
    tol = 1e-4,
    random_state = 42
)

In [186]:
rid.fit(X_train, y_train)

Ridge(alpha=10, random_state=42, solver='saga')

In [187]:
y_preds = rid.predict(X_test)

In [188]:
from sklearn.metrics import r2_score

In [189]:
r2_score(y_test, y_preds)

0.6613547575262211

What is the index of most important feature? Note the index starts from 0. Ignore the intercept for this question.

In [193]:
abs(rid.coef_).argmax()

np.int64(9)

What is the index of least important feature? Note the index starts from 0. Ignore the intercept for this question.

In [194]:
abs(rid.coef_).argmin()

np.int64(0)


6 points
(Common Instructions for Q.5 and Q.6)
Take SGDRegressor(random_state = 42) estimator with GridSearchCV. Hyperparameter tuning to be done over the following parameters:

penalty as ['l1', 'l2']

alpha values as [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]

values of tol as [1e-4, 1e-3, 1e-2, 1e-1]

Use cross-validation = 5

Set scoring as neg_mean_absolute_error

Use the best model from above hyper parameter tuning process to answer following questions:

What is the best penalty?

In [195]:
from sklearn.linear_model import SGDRegressor

In [196]:
sgd = SGDRegressor(random_state = 42)

In [199]:
from sklearn.model_selection import GridSearchCV

In [200]:
params = {
    "penalty": ['l1', 'l2'],
    "alpha": [1e-5, 1e-4, 1e-3, 1e-2, 1e-1],
    "tol": [1e-4, 1e-3, 1e-2, 1e-1],
}

grid = GridSearchCV(
    estimator = sgd,
    param_grid = params,
    cv = 5,
    scoring = "neg_mean_absolute_error"
)

In [203]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SGDRegressor(random_state=42),
             param_grid={'alpha': [1e-05, 0.0001, 0.001, 0.01, 0.1],
                         'penalty': ['l1', 'l2'],
                         'tol': [0.0001, 0.001, 0.01, 0.1]},
             scoring='neg_mean_absolute_error')

In [204]:
grid.best_params_["penalty"]

'l2'

What will be value of mean absolute error on the test dataset?

In [205]:
from sklearn.metrics import mean_absolute_error

In [206]:
model = grid.best_estimator_

In [207]:
y_preds = model.predict(X_test)

In [208]:
mean_absolute_error(y_test, y_preds)

3.8131121797994014


(Common Instructions for Q.7 and Q.8)

Create a pipeline of the PCA() as transformer and Lasso as an estimator.

Use GridSearchCV for tuning the hyperparameters of the created pipeline on training dataset.

1. Values of n_components for PCA to be [0.9, 0.95]

2. lasso alpha value to be taken as : [10, 1, 0.01, 0.001]

3. scoring : neg_mean_absolute_error.
4. Use 5 fold cross validation.

5. n_jobs = -1 (negative one) [it helps in using all the computational power to run this job]

(Note: Kindly ignore the warning.)

If we fit the pipeline on the training dataset, what will be the R2 score on the test dataset?

In [209]:
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Lasso

In [210]:
pipe = Pipeline([
    ('pca', PCA()),
    ('las', Lasso())
])

In [211]:
params = {
    'pca__n_components': [0.9, 0.95],
    'las__alpha': [10, 1, 0.01, 0.001]
}

In [212]:
grid = GridSearchCV(
    estimator = pipe,
    param_grid = params,
    cv = 5,
    scoring = "neg_mean_absolute_error",
    n_jobs = -1
)

In [213]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Pipeline(steps=[('pca', PCA()), ('las', Lasso())]),
             n_jobs=-1,
             param_grid={'las__alpha': [10, 1, 0.01, 0.001],
                         'pca__n_components': [0.9, 0.95]},
             scoring='neg_mean_absolute_error')

In [215]:
model = grid.best_estimator_

In [216]:
y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)

print("R2 score on test data:", r2)

R2 score on test data: 0.6288625430197575

How much variance is explained (Eigen value) by the first principle component?

In [218]:
model.named_steps['pca'].explained_variance_[0]

np.float64(1.1635075742239045)


Create a pipeline of the PolynomialFeatures as transformer and Lasso as an estimator with the following parameters:
  - For PolynomialFeatures:
    - interaction_only = False
    - degree = 2
  - For Lasso:
    - alpha = 1
    - warm_start = True
    - random state as 0

Fit the pipeline on the training dataset and find the
R
2
R
2
  score on the test dataset.

In [219]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score

pipe = Pipeline([
    ('poly', PolynomialFeatures(degree=2, interaction_only=False)),
    ('lasso', Lasso(alpha=1, warm_start=True, random_state=0))
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

r2 = r2_score(y_test, y_pred)

print("R2 score on test data:", r2)

R2 score on test data: 0.157678032410551

If you eliminate 1 feature with recursive feature elimination, which feature will be eliminated?
Type the index of the eliminated feature (index starts from 0).

Use LinearRegression
 model with default parameters as an estimator.
Use processed training data.

In [220]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

model = LinearRegression()

rfe = RFE(estimator=model, n_features_to_select=X_train.shape[1] - 1)

rfe.fit(X_train, y_train)

eliminated_feature_index = list(rfe.support_).index(False)

print("Eliminated feature index:", eliminated_feature_index)

Eliminated feature index: 2